version: '3'
services:
  app:
    build: ./app
    links:
     - db
    ports:
     - "5001:5000"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    

    
